spring.application.name=project2


# ===============================
# Database Connection Settings
# ===============================
# Format: ${ENVIRONMENT_VARIABLE_NAME:fallback_value_if_not_provided}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/online_shop?useSSL=false&serverTimezone=UTC}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:default}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# =============================== 361fkl
# JPA / Hibernate Settings
# ===============================

# Controls how Hibernate alters your database schema (e.g., update, create, create-drop, validate, none)
spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL_AUTO:update}

# Whether to print SQL queries to the console (useful for debugging, bad for production logs)
spring.jpa.show-sql=${HIBERNATE_SHOW_SQL:false}

# Explicitly sets the MySQL dialect so Hibernate knows how to format the SQL
spring.jpa.database-platform=${HIBERNATE_DIALECT:org.hibernate.dialect.MySQLDialect}